### ISSUE TITLE
求教：为什么在部署完成后不销毁另一个实例呢？

### ISSUE THREAD

**Issue by uyoufu** [airyland/egg-deploy#8]
初步使用了一下，我发现 deploy 之后，会有两个 eggjs 实例运行，想请教下，为什么在 deploy 完成之后，不销毁另一个实例呢？因为像定时任务这种，就会被执行两次。

**Comment by airyland** [comment]
如果是配置两个端口确实是两个实例在运行，当时实现时没考虑太完善。egg 现在看起来有很多不完善的设计，所以我目前没再维护了。
